export const staticAsset = (filename: string) => `${import.meta.env.BASE_URL}assets/${filename}`;

export const categoryDefinitions = [
  {
    id: "text-based",
    number: "01",
    title: "Text-Based Learning Materials",
    shortTitle: "Text-based",
    description: "Printable, editable resources for reading, vocabulary, speaking and language assessment.",
  },
  {
    id: "visual",
    number: "02",
    title: "Visual Learning Materials",
    shortTitle: "Visual",
    description: "Image-led resources that make vocabulary, ideas and classroom explanations more memorable.",
  },
  {
    id: "video",
    number: "03",
    title: "Video Learning Materials",
    shortTitle: "Video",
    description: "Production systems for creating purposeful short films and discussion-rich viewing experiences.",
  },
  {
    id: "interactive",
    number: "04",
    title: "Interactive & Web-Based Materials",
    shortTitle: "Interactive",
    description: "Responsive practice sites, live learning displays and conversational experiences for students.",
  },
] as const;

export type ResourceCategory = (typeof categoryDefinitions)[number]["id"];
export type SampleType = "download" | "live-site" | "video" | "ai-tool";

export type CatalogueResource = {
  order: number;
  slug: string;
  title: string;
  shortTitle: string;
  category: ResourceCategory;
  summary: string;
  guideUrl: string;
  previewUrl: string;
  previewAlt: string;
  sampleType: SampleType;
  sampleUrl: string;
  outputLabel: string;
  featured?: boolean;
  tags: string[];
};

export const resourceCatalogue: CatalogueResource[] = [
  {
    order: 1,
    slug: "dse-english-vocabulary-glossary-from-a-reading-passage",
    title: "DSE English Vocabulary Glossary from a Reading Passage",
    shortTitle: "DSE Vocabulary Glossary",
    category: "text-based",
    summary: "A completed DSE reading glossary with line numbers, verified CEFR levels, Traditional Chinese meanings and original examples.",
    guideUrl: staticAsset("dse-english-vocabulary-glossary-from-a-reading-passage_c675ce69.md"),
    previewUrl: staticAsset("dse-english-vocabulary-glossary-from-a-reading-passage-preview_80d001f0.webp"),
    previewAlt: "First page of a DSE English vocabulary glossary with CEFR levels, Chinese definitions and example sentences.",
    sampleType: "download",
    sampleUrl: staticAsset("dse-english-vocabulary-glossary-from-a-reading-passage_7330747c.pdf"),
    outputLabel: "PDF sample",
    featured: true,
    tags: ["DSE", "Vocabulary", "CEFR", "Reading"],
  },
  {
    order: 2,
    slug: "dse-news-article-cloze-exercise",
    title: "DSE News Article Cloze Exercise",
    shortTitle: "News Article Cloze",
    category: "text-based",
    summary: "An HKDSE-style cloze activity with a checked transcription, student worksheet and two levels of answer key.",
    guideUrl: staticAsset("dse-news-article-cloze-exercise_da4b8e58.md"),
    previewUrl: staticAsset("dse-news-article-cloze-exercise-preview_47446c60.webp"),
    previewAlt: "Preview of an HKDSE-style news article cloze worksheet arranged on a warm paper stage.",
    sampleType: "download",
    sampleUrl: staticAsset("dse-news-article-cloze-exercise_06073d74.pdf"),
    outputLabel: "PDF sample",
    tags: ["DSE", "Cloze", "News", "B2"],
  },
  {
    order: 3,
    slug: "dse-news-fact-sheet-cloze-exercise",
    title: "DSE News Fact-Sheet Cloze Exercise",
    shortTitle: "News Fact-Sheet Cloze",
    category: "text-based",
    summary: "A news-based HKDSE Fact Sheet with 15 blanks, checked transcription, student answers and detailed teacher notes.",
    guideUrl: staticAsset("dse-news-fact-sheet-cloze-exercise_130d9986.md"),
    previewUrl: staticAsset("dse-news-fact-sheet-cloze-exercise-preview_7ef5bd54.webp"),
    previewAlt: "Preview of a news-based HKDSE Fact Sheet cloze exercise on a layered paper stage.",
    sampleType: "download",
    sampleUrl: staticAsset("dse-news-fact-sheet-cloze-exercise_ccf62df2.pdf"),
    outputLabel: "PDF sample",
    tags: ["DSE", "Fact Sheet", "Cloze", "News"],
  },
  {
    order: 4,
    slug: "dse-news-article-proofreading-exercise",
    title: "DSE News-Article Proofreading Exercise",
    shortTitle: "News Proofreading Exercise",
    category: "text-based",
    summary: "A three-part HKDSE English proofreading worksheet with a student version, answer key and word-source record.",
    guideUrl: staticAsset("dse-news-article-proofreading-exercise_e7051bf4.md"),
    previewUrl: staticAsset("dse-news-article-proofreading-exercise-preview_4bdf4e8b.webp"),
    previewAlt: "Preview of a three-part HKDSE news-article proofreading worksheet.",
    sampleType: "download",
    sampleUrl: staticAsset("dse-news-article-proofreading-exercise_ca64e88e.pdf"),
    outputLabel: "PDF sample",
    tags: ["DSE", "Proofreading", "News", "Grammar"],
  },
  {
    order: 5,
    slug: "dse-paper-4-group-interaction-speaking-ideas-handout",
    title: "DSE Paper 4 Group Interaction Speaking-Ideas Handout",
    shortTitle: "Speaking-Ideas Handout",
    category: "text-based",
    summary: "A print-ready debriefing handout with concise, balanced ideas for HKDSE Paper 4 Group Interaction.",
    guideUrl: staticAsset("dse-paper-4-group-interaction-speaking-ideas-handout_f677b797.md"),
    previewUrl: staticAsset("dse-paper-4-group-interaction-speaking-ideas-handout-preview_37c8bfd9.webp"),
    previewAlt: "Preview of a print-ready HKDSE Paper 4 group interaction ideas handout.",
    sampleType: "download",
    sampleUrl: staticAsset("dse-paper-4-group-interaction-speaking-ideas-handout_c173fba5.pdf"),
    outputLabel: "PDF sample",
    tags: ["DSE", "Speaking", "Paper 4", "Ideas"],
  },
  {
    order: 6,
    slug: "grammar-answer-judge-report",
    title: "Grammar Answer Judge Report",
    shortTitle: "Grammar Answer Judge",
    category: "text-based",
    summary: "A teacher-facing report with separate lenient and strict decisions, reasoning and practical marking advice.",
    guideUrl: staticAsset("grammar-answer-judge-report_a6d1e746.md"),
    previewUrl: staticAsset("grammar-answer-judge-report-preview_97e156ef.webp"),
    previewAlt: "Preview of a branded grammar-answer judgement report for teachers.",
    sampleType: "download",
    sampleUrl: staticAsset("grammar-answer-judge-report_53470db1.pdf"),
    outputLabel: "PDF sample",
    tags: ["Grammar", "Assessment", "Marking", "Teacher Report"],
  },
  {
    order: 7,
    slug: "oxford-vocabulary-multiple-choice-cloze-exercise",
    title: "Oxford Vocabulary Multiple-Choice Cloze Exercise",
    shortTitle: "Oxford MC Cloze",
    category: "text-based",
    summary: "A Word multiple-choice cloze exercise built from an Oxford vocabulary spreadsheet, with 12 questions and an answer version.",
    guideUrl: staticAsset("oxford-vocabulary-multiple-choice-cloze-exercise_b4022ed2.md"),
    previewUrl: staticAsset("oxford-vocabulary-multiple-choice-cloze-exercise-preview_755b0843.webp"),
    previewAlt: "Preview of an Oxford vocabulary multiple-choice cloze exercise.",
    sampleType: "download",
    sampleUrl: staticAsset("oxford-vocabulary-multiple-choice-cloze-exercise_dd688595.pdf"),
    outputLabel: "PDF sample",
    tags: ["Oxford", "Vocabulary", "Multiple Choice", "Cloze"],
  },
  {
    order: 8,
    slug: "labelled-vocabulary-image-for-powerpoint",
    title: "Labelled Vocabulary Image for PowerPoint",
    shortTitle: "Labelled Vocabulary Image",
    category: "visual",
    summary: "One coherent 16:9 scene that helps learners connect three to six target words with clear visual examples.",
    guideUrl: staticAsset("labelled-vocabulary-image-for-powerpoint_3f244484.md"),
    previewUrl: staticAsset("labelled-vocabulary-image-for-powerpoint-preview_b057646b.webp"),
    previewAlt: "Preview of a labelled 16:9 vocabulary image designed for a PowerPoint slide.",
    sampleType: "download",
    sampleUrl: staticAsset("labelled-vocabulary-image-for-powerpoint_8cb13a19.pdf"),
    outputLabel: "PDF samples",
    featured: true,
    tags: ["Vocabulary", "PowerPoint", "Visual", "Image"],
  },
  {
    order: 9,
    slug: "print-friendly-educational-infographic",
    title: "Print-Friendly Educational Infographic",
    shortTitle: "Educational Infographic",
    category: "visual",
    summary: "A clear single-page infographic that preserves supplied wording and remains economical to print for secondary students.",
    guideUrl: staticAsset("print-friendly-educational-infographic_9fc13317.md"),
    previewUrl: staticAsset("print-friendly-educational-infographic-preview_28ead5fd.webp"),
    previewAlt: "Preview of a clear, modern and print-friendly educational infographic.",
    sampleType: "download",
    sampleUrl: staticAsset("print-friendly-educational-infographic_1dea7f3d.pdf"),
    outputLabel: "PDF samples",
    tags: ["Infographic", "Print", "Visual", "Secondary"],
  },
  {
    order: 10,
    slug: "pokemon-style-vocabulary-cards",
    title: "Pokémon-Style Vocabulary Cards",
    shortTitle: "Vocabulary Creature Cards",
    category: "visual",
    summary: "A set of polished vocabulary cards combining bilingual definitions, examples, CEFR labels and original creature illustrations.",
    guideUrl: staticAsset("pokemon-style-vocabulary-cards_62d989ba.md"),
    previewUrl: staticAsset("pokemon-style-vocabulary-cards-preview_b8b1c91e.webp"),
    previewAlt: "Preview of colourful creature-themed vocabulary cards for Secondary 2 learners.",
    sampleType: "download",
    sampleUrl: staticAsset("pokemon-style-vocabulary-cards_40a0d18c.pdf"),
    outputLabel: "PDF samples",
    tags: ["Vocabulary", "Cards", "CEFR", "Illustration"],
  },
  {
    order: 11,
    slug: "ai-short-film-production",
    title: "AI Short-Film Production",
    shortTitle: "AI Short-Film Production",
    category: "video",
    summary: "A complete short-film production pack with character guides, timed shots, dialogue, sound notes and generation prompts.",
    guideUrl: staticAsset("ai-short-film-production_b3b3064c.md"),
    previewUrl: staticAsset("ai-short-film-production-preview_2118c83e.jpg"),
    previewAlt: "Animated schoolgirl in a sunlit school corridor from the AI short film.",
    sampleType: "video",
    sampleUrl: "https://www.youtube.com/watch?v=sHrGaJAUZQk",
    outputLabel: "Watch video",
    featured: true,
    tags: ["Video", "Film", "Storytelling", "Discussion"],
  },
  {
    order: 12,
    slug: "vocabulary-revision-website",
    title: "Vocabulary Revision Website",
    shortTitle: "Vocabulary Revision Website",
    category: "interactive",
    summary: "A responsive Secondary 2 vocabulary exercise with varied practice questions, revision flashcards, feedback and results.",
    guideUrl: staticAsset("s2-vocabulary-revision-website_46636c9c.md"),
    previewUrl: staticAsset("vocabulary-revision-website-preview_a94e7859.webp"),
    previewAlt: "S2 Vocabulary Revision website challenge setup screen.",
    sampleType: "live-site",
    sampleUrl: "https://ksloenglish.github.io/s2-vocab/",
    outputLabel: "Open live website",
    tags: ["Vocabulary", "Website", "Secondary 2", "Revision"],
  },
  {
    order: 13,
    slug: "four-option-vocabulary-practice-website",
    title: "Four-Option Vocabulary Practice Website",
    shortTitle: "Four-Option Vocabulary Practice",
    category: "interactive",
    summary: "A responsive sentence-completion website using reviewed question data, four options and British English throughout.",
    guideUrl: staticAsset("four-option-vocabulary-practice-website_2e2d99bc.md"),
    previewUrl: staticAsset("four-option-vocabulary-practice-website-preview_3ba40f77.webp"),
    previewAlt: "Oxbridge Vocabulary Challenge website configuration screen.",
    sampleType: "live-site",
    sampleUrl: "https://ksloenglish.github.io/oxbridge-vocab/",
    outputLabel: "Open live website",
    tags: ["Vocabulary", "Website", "Oxford 5000", "Cambridge C2"],
  },
  {
    order: 14,
    slug: "grammar-challenge-website",
    title: "Grammar Challenge Website",
    shortTitle: "Grammar Challenge Website",
    category: "interactive",
    summary: "A polished grammar practice site with random runs, automatic marking, a timer, final score and complete answer review.",
    guideUrl: staticAsset("grammar-challenge-website_a5eda917.md"),
    previewUrl: staticAsset("grammar-challenge-website-preview_2fb462cb.webp"),
    previewAlt: "S2 Grammar Challenge website quest-selection screen.",
    sampleType: "live-site",
    sampleUrl: "https://ksloenglish.github.io/s2-grammar/",
    outputLabel: "Open live website",
    tags: ["Grammar", "Website", "Secondary 2", "Practice"],
  },
  {
    order: 15,
    slug: "solidmemory-leaderboard-and-awards-website",
    title: "SolidMemory Leaderboard and Awards Website",
    shortTitle: "SolidMemory Leaderboards",
    category: "interactive",
    summary: "A mobile-friendly school website with live leaderboards, official awards, protected administration and reliable ranking rules.",
    guideUrl: staticAsset("solidmemory-leaderboard-and-awards-website_5f432688.md"),
    previewUrl: staticAsset("r15-solidmemory-leaderboards-preview_84903cd9.webp"),
    previewAlt: "SolidMemory monthly S1 leaderboard showing the ranking table, date range and navigation tabs.",
    sampleType: "live-site",
    sampleUrl: "https://kslosmem.manus.space/",
    outputLabel: "Open live website",
    tags: ["Leaderboard", "Awards", "Website", "SolidMemory"],
  },
  {
    order: 16,
    slug: "historical-interview-character-for-students",
    title: "Historical Interview Character for Students",
    shortTitle: "Historical Interview Character",
    category: "interactive",
    summary: "A ready-to-use AI historical character that helps students practise interviewing, note-taking and biographical writing.",
    guideUrl: staticAsset("historical-interview-character-for-students_54cba2d7.md"),
    previewUrl: staticAsset("r16-historical-interview-conversation-preview_8efd884c.webp"),
    previewAlt: "Gemini conversation demonstrating a student interview with a custom historical character based on Alfonso Wong.",
    sampleType: "ai-tool",
    sampleUrl: "https://gemini.google.com/gem/1bHc2gEHd9IxqlCsrztweTuctZZlMzgDO?usp=sharing",
    outputLabel: "Open Gemini character",
    tags: ["AI Character", "Interview", "Biography", "Speaking"],
  },
];

export const resourceBySlug = Object.fromEntries(
  resourceCatalogue.map(resource => [resource.slug, resource]),
) as Record<string, CatalogueResource>;
